package datrik;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imag/Menu_icon.png"));
        setIconImage(icon);
        
//        this.setResizable(false);
        this.setLocationRelativeTo(null);
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                close();
            }

            private void close() {
                if (JOptionPane.showConfirmDialog(rootPane, "¿Desea realmente salir del sistema?",
                        "Salir del sistema", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                    System.exit(0);
                }
            }
        });
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        vocales = new javax.swing.JButton();
        abecedario = new javax.swing.JButton();
        silabas = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        vocales.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        vocales.setText("VOCALES");
        vocales.setBorder(null);
        vocales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vocalesActionPerformed(evt);
            }
        });
        getContentPane().add(vocales, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 240, 100));

        abecedario.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        abecedario.setText("ABECEDARIO");
        abecedario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abecedarioActionPerformed(evt);
            }
        });
        private void vocalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vocalesActionPerformed
            Vocales v = new Vocales();
            v.setVisible(true);
            Menu.this.dispose();
         private void silabasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silabasActionPerformed
                Silabas s = new Silabas();
                s.setVisible(true);
                Menu.this.dispose();
            }//GEN-LAST:event_silabasActionPerformed
 // Variables declaration - do not modify//GEN-BEGIN:variables
 private javax.swing.JButton abecedario;
 private javax.swing.JButton jButton1;
 private javax.swing.JLabel jLabel1;
 private javax.swing.JLabel jLabel2;
 private javax.swing.JButton silabas;
 private javax.swing.JButton vocales;
 // End of variables declaration//GEN-END:variables
}
